import streamlit as st
import requests

# Configure the page
st.set_page_config(page_title="AiCodeReviewer", page_icon="🤖", layout="wide")

st.title("AiCodeReviewer 🤖")
st.markdown("Submit your Python code for an automated AI review to detect PEP8 violations, clean code issues, security vulnerabilities, bugs, and performance problems.")

# Settings Sidebar for the Ngrok API URL
with st.sidebar:
    st.header("⚙️ API Configuration")
    st.markdown("Enter the Ngrok public URL generated by your Kaggle notebook.")
    api_url = st.text_input("Kaggle Ngrok URL", placeholder="https://<your-id>.ngrok-free.app")
    
    # Ensure the URL is correctly formatted with the endpoint
    if api_url and not api_url.endswith("/review"):
        api_url = api_url.rstrip("/") + "/review"

# Main Interface for Code Input
st.subheader("Code Input")
code_input = st.text_area("Paste your Python code below:", height=300, placeholder="def my_function():\n    pass")

if st.button("Review Code", type="primary"):
    if not api_url:
        st.warning("Please configure your Kaggle Ngrok URL in the sidebar first.")
    elif not code_input.strip():
        st.warning("Please paste some code to be reviewed.")
    else:
        with st.spinner("Analyzing code... This might take a few moments."):
            try:
                # Send the POST request to the FastAPI backend running on Kaggle
                response = requests.post(api_url, json={"code": code_input})
                
                # Check if the request was successful
                if response.status_code == 200:
                    report = response.json()
                    
                    if "error" in report:
                        st.error(f"API Error: {report['error']}")
                    else:
                        st.success(f"Review Complete for: {report.get('file', 'Uploaded Snippet')}")
                        
                        issues = report.get('issues', [])
                        
                        if not issues:
                            st.info("No issues found! Your code looks great. 🎉")
                        else:
                            st.subheader(f"Found {len(issues)} Issue(s)")
                            
                            # Parse and display each issue from the Pydantic schema
                            for issue in issues:
                                severity = issue.get("severity", "Unknown").lower()
                                
                                # Set a visual indicator based on severity
                                if severity == "high":
                                    icon = "🚨"
                                elif severity == "medium":
                                    icon = "⚠️"
                                else:
                                    icon = "ℹ️"
                                    
                                with st.expander(f"{icon} Line {issue.get('line')}: {issue.get('issue')} ({severity.capitalize()})"):
                                    st.markdown("**Explanation:**")
                                    st.write(issue.get("explanation"))
                                    
                                    st.markdown("**Suggested Fix:**")
                                    st.code(issue.get("suggested_fix"), language="python")
                                    
                else:
                    st.error(f"Failed to connect. Server returned status code: {response.status_code}")
                    st.write("Response details:", response.text)
                    
            except requests.exceptions.RequestException as e:
                st.error("Network Error: Could not reach the API. Please check if your Ngrok tunnel is still running and the URL is correct.")
                st.exception(e)