import streamlit as st
import requests

# Configure the page
st.set_page_config(page_title="AiCodeReviewer", page_icon="🤖", layout="wide")

st.title("AiCodeReviewer 🤖")
st.markdown("Submit your Python code for an automated AI review to detect PEP8 violations, clean code issues, security vulnerabilities, bugs, and performance problems.")

# Settings Sidebar for the Ngrok API URL
with st.sidebar:
    st.header("⚙️ API Configuration")
    st.markdown("Enter the Ngrok public URL generated by your Kaggle notebook.")
    api_url = st.text_input("Kaggle Ngrok URL", placeholder="https://<your-id>.ngrok-free.app")

    # Ensure the URL is correctly formatted with the endpoint
    if api_url and not api_url.endswith("/review"):
        api_url = api_url.rstrip("/") + "/review"

    timeout_seconds = st.slider(
        "Request timeout (seconds)",
        min_value=30,
        max_value=600,
        value=180,
        step=30,
        help="LLM inference can be slow on a shared Kaggle GPU. Raise this if you keep getting timeout errors on longer snippets."
    )

# Main Interface for Code Input
st.subheader("Code Input")
code_input = st.text_area("Paste your Python code below:", height=300, placeholder="def my_function():\n    pass")

if st.button("Review Code", type="primary"):
    if not api_url:
        st.warning("Please configure your Kaggle Ngrok URL in the sidebar first.")
    elif not code_input.strip():
        st.warning("Please paste some code to be reviewed.")
    else:
        with st.spinner("Analyzing code... This might take a few moments."):
            try:
                # Send the POST request to the FastAPI backend running on Kaggle.
                # NOTE: "ngrok-skip-browser-warning" is required for free ngrok
                # tunnels (*.ngrok-free.app) — without it, ngrok returns an HTML
                # interstitial warning page instead of forwarding the request,
                # and response.json() below would fail on that HTML.
                response = requests.post(
                    api_url,
                    json={"code": code_input},
                    headers={"ngrok-skip-browser-warning": "true"},
                    timeout=timeout_seconds,
                )

                # Check if the request was successful
                if response.status_code == 200:
                    content_type = response.headers.get("content-type", "")

                    if "application/json" not in content_type:
                        # Most common cause: ngrok interstitial page or a
                        # non-JSON error page slipped through despite the header,
                        # or the tunnel URL is stale/wrong.
                        st.error(
                            "The server responded with a 200 status but didn't return JSON. "
                            "This usually means the Ngrok URL is stale, the tunnel restarted, "
                            "or you're hitting a non-API page."
                        )
                        with st.expander("Raw response (for debugging)"):
                            st.code(response.text[:2000])
                    else:
                        try:
                            report = response.json()
                        except requests.exceptions.JSONDecodeError:
                            st.error("Received malformed JSON from the API.")
                            with st.expander("Raw response (for debugging)"):
                                st.code(response.text[:2000])
                            report = None

                        if report is not None:
                            if "error" in report:
                                st.error(f"API Error: {report['error']}")
                                st.caption(
                                    "This error came from the model/parsing step on the Kaggle side "
                                    "(e.g. the LLM's output didn't match the expected structured format), "
                                    "not from the network connection."
                                )
                            else:
                                st.success(f"Review Complete for: {report.get('file', 'Uploaded Snippet')}")

                                issues = report.get('issues', [])

                                if not issues:
                                    st.info("No issues found! Your code looks great. 🎉")
                                else:
                                    st.subheader(f"Found {len(issues)} Issue(s)")

                                    # Parse and display each issue from the Pydantic schema
                                    for issue in issues:
                                        severity = issue.get("severity", "Unknown").lower()

                                        # Set a visual indicator based on severity
                                        if severity == "high":
                                            icon = "🚨"
                                        elif severity == "medium":
                                            icon = "⚠️"
                                        else:
                                            icon = "ℹ️"

                                        with st.expander(f"{icon} Line {issue.get('line')}: {issue.get('issue')} ({severity.capitalize()})"):
                                            st.markdown("**Explanation:**")
                                            st.write(issue.get("explanation"))

                                            st.markdown("**Suggested Fix:**")
                                            st.code(issue.get("suggested_fix"), language="python")

                elif response.status_code in (401, 403, 404, 429, 503, 511):
                    # 511 is what ngrok's free-tier interstitial sometimes surfaces as;
                    # 404 usually means a stale/incorrect tunnel URL.
                    st.error(f"Server returned status code: {response.status_code}")
                    st.write("Response details:", response.text[:2000])
                else:
                    st.error(f"Failed to connect. Server returned status code: {response.status_code}")
                    st.write("Response details:", response.text[:2000])

            except requests.exceptions.Timeout:
                st.error(
                    f"Request timed out after {timeout_seconds}s. The Kaggle GPU may be busy, "
                    "or your Kaggle session/ngrok tunnel may have disconnected. "
                    "Try raising the timeout in the sidebar, or re-check that the notebook is still running."
                )
            except requests.exceptions.ConnectionError as e:
                st.error(
                    "Network Error: Could not reach the API. This usually means the Ngrok tunnel "
                    "has stopped (Kaggle session ended/restarted) or the URL was copied incorrectly."
                )
                st.exception(e)
            except requests.exceptions.RequestException as e:
                st.error("Network Error: Could not reach the API. Please check if your Ngrok tunnel is still running and the URL is correct.")
                st.exception(e)